### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by stsewd** [Odoo-EC/odoo_installer#1]
Hola, ya que agregaste este proyecto en https://github.com/pythonecuador/floss-ecuador/pull/3, me olvidé revisar la licencia antes de hacerle merge. Podrías agregar una licencia FLOSS a este proyecto? Gracias.

Lo puedes hacer desde la interfaz web de GitHub https://github.com/Odoo-EC/odoo_installer/community/license/new?branch=15.0

**Comment by celm1990** [comment]
Realizado en el commit 
https://github.com/Odoo-EC/odoo_installer/commit/f0bc322c173778b1fc27a53f71219280a67074dc
